version: '3'

services:
  backup:
    container_name: mssql-backuper
    build:
      context: ./build/
      dockerfile: Dockerfile
    image: mds:latest
    volumes: 
      - ./backup:/app/backup/
      - ./backup.log:/app/backup.log
    env_file:
      - .env
    restart: 'on-failure'
    
